### ISSUE TITLE
Error in phpDoc generation

### ISSUE THREAD

**Issue by moffe42** [spf13/PIV#1]
"pdv_cfg_CommentEnd" is not defind. So an error is generated when using ,pd on methods

**Comment by yuxel** [comment]
I can reproduce this bug. 
When typing ",pd" on a function line, it gives these errors,

<pre>
Error detected while processing function 
PhpDocSingle..PhpDoc..PhpDocFunc..PhpDocFuncEndAuto:                                                                                                          
Undefined variable: g:pdv_cfg_CommentEnd
Invalid arguments for function append
</pre>

**Comment by spf13** [comment]
This issue is fixed in the latest release.

**Comment by yuxel** [comment]
Thanks for fixing this issue.

**Comment by johncongdon** [comment]
I am still getting this error, and I just installed today from github.  Am I missing the latest release somehow?

**Comment by ghost** [comment]
same here, freshly installed from github "Undefined variable: g:pdv_cfg_CommentEnd" when I hit ',pd'

**Comment by ghost** [comment]
actually, the version of piv/ftplugin/php/doc.vim installed via spf13-vim is out of date. I think I'm going to have to get rid of spf13-vim, it's very buggy*

[edit] \* I take that back, it's not 'very buggy' at all

**Comment by spf13** [comment]
I'm happy to help resolve any issues. I'll checkout and see if I can reproduce. In the meantime, I recommend checkout out the 3.0 branch of spf13-vim. It's quite close to ready for production use and resolves many of the current issues in spf13-vim. I'm expecting to release it in the next couple weeks and would love some more real world feedback.

**Comment by spf13** [comment]
Enough feedback that it's not resolved, I'm looking into the issue now.

**Comment by ghost** [comment]
I can see the declaration of pdv_cfg_CommentEnd in the PIV repo, but the line is not there in my local copy after checking out the spf13-vim repo. which is very odd as piv is included as a submodule in spf13-vim

Thanks for looking into this, I'll take a look at v3.0 and see how I get on

**Comment by spf13** [comment]
One of the problems with using git submodules to handle plugins is they point to a specific refspec (commit). It means that every time any of the plugins have a new version I need to manually update the refspec the submodule is pointing to. 

The 3.0 branch is using vundle which simply points to the head of a git repo which is a much better fit for spf13-vim. Over half the reported bugs were directly the result of issues with submodule pointers. 

I'm really interested in how you like 3.0. Please email me and let me know.

**Comment by spf13** [comment]
This has been resolved in HEAD and 3.0.
